task:
  name: MacOS
  macos_instance:
    image: ghcr.io/cirruslabs/macos-runner:sonoma
  bootstrap_script:
    - ./configure
    - make
    - sudo make install
    - make distclean
  selftest_script:
    - ./configure
    - mk
    - sudo mk install
