.Dd $Mdocdate$
.Dt MK 1
.Os
.Sh NAME
.Nm mk
.Nd build stuff
.Sh SYNOPSIS
.Nm
.Op Fl hkpsSv
.Op Fl C Ar dir
.Op Fl f Ar makefile
.Op Fl o Ar objdir
.Op Fl V Ar var
.Op Ar target ...
.Sh DESCRIPTION
.Nm
is designed to help you build stuff.
It is specifically designed for larger projects,
for which
.Xr make 1
is not suitable enough.
.Sh ENVIRONMENT
.Sh FILES
.Sh EXIT STATUS
.Sh EXAMPLES
.Ex -std
.Sh SEE ALSO
.Xr make 1
.Sh STANDARDS
.Sh HISTORY
.Sh AUTHORS
.Sh CAVEATS
.Sh BUGS
